// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyghgyzhxaxlyikwmuor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5Z2hneXpoeGF4bHlpa3dtdW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NzQ2NjUsImV4cCI6MjA1NzE1MDY2NX0.jf60oylPdKjnalGNDOJf-RG1k7dJZNwVNyTtWxxTrI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);